import XCTest
@testable import SeenAt
import SwiftData

@MainActor
final class MigrationTests: XCTestCase {
    private func createV1Store(at url: URL) {
        let config = ModelConfiguration(url: url)
        let container = try! ModelContainer(
            for: SeenAtSchemaV1.Team.self, SeenAtSchemaV1.Event.self, SeenAtSchemaV1.JerseySighting.self,
            configurations: config
        )
        let context = container.mainContext

        let event1 = SeenAtSchemaV1.Event(title: "Yankees @ Red Sox", date: Date())
        context.insert(event1)

        let event2 = SeenAtSchemaV1.Event(title: "Cubs @ Cardinals", date: Date())
        context.insert(event2)

        let event3 = SeenAtSchemaV1.Event(title: "No teams here", date: Date())
        context.insert(event3)

        try! context.save()
    }

    func testV1ToV2MigrationPopulatesAwayAndHomeTeams() throws {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("migration_\(UUID().uuidString).sqlite")
        defer { try? FileManager.default.removeItem(at: url) }

        createV1Store(at: url)

        let config = ModelConfiguration(url: url)
        let container = try ModelContainer(
            for: Team.self, Event.self, JerseySighting.self,
            migrationPlan: SeenAtMigrationPlan.self,
            configurations: config
        )

        let descriptor = FetchDescriptor<Event>(sortBy: [SortDescriptor(\.title)])
        let events = try container.mainContext.fetch(descriptor)

        XCTAssertEqual(events.count, 3)

        let yankees = events.first { $0.title == "Yankees @ Red Sox" }
        XCTAssertEqual(yankees?.awayTeam, "Yankees")
        XCTAssertEqual(yankees?.homeTeam, "Red Sox")

        let cubs = events.first { $0.title == "Cubs @ Cardinals" }
        XCTAssertEqual(cubs?.awayTeam, "Cubs")
        XCTAssertEqual(cubs?.homeTeam, "Cardinals")

        let noTeams = events.first { $0.title == "No teams here" }
        XCTAssertNil(noTeams?.awayTeam)
        XCTAssertNil(noTeams?.homeTeam)

        // id should be auto-generated by the migration engine
        for event in events {
            XCTAssertNotEqual(event.id.uuidString, "00000000-0000-0000-0000-000000000000")
        }
    }
}
